sudo: required
services:
  - docker

before_install:
  - docker build -t amigochoi/react-test -f ./client/Dockerfile.dev ./client

# exit other than 0 = fail
script: 
  - docker run amigochoi/react-test npm test -- --coverage

after_success:
  - docker build -t amigochoi/multi-client ./client
  - docker build -t amigochoi/multi-nginx ./nginx
  - docker build -t amigochoi/multi-server ./server
  - docker build -t amigochoi/multi-worker ./worker

  # Login in to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those iages and push them to docker hub
  - docker push amigochoi/multi-client
  - docker push amigochoi/multi-nginx
  - docker push amigochoi/multi-server
  - docker push amigochoi/multi-worker